import { Poppins } from "next/font/google";
import "./globals.css";

// Font Google Poppins
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// Metadata halaman
export const metadata = {
  title: "Laporan Wakaf Bulanan Laz",
  description: "Generated by create next app",
};

// Layout utama
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body data-theme="light" className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
