import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

// Konfigurasi font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// Metadata halaman
export const metadata = {
  title: "Laporan Wakaf Bulanan Laz",
  description: "Generated by create next app",
};

// Layout utama
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        data-theme="light"
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
